### ISSUE TITLE
"scsi command failed"

### ISSUE THREAD

**Issue by mlgmaster666** [zhaoyangwx/LTFSCopyGUI#4]
Hi, i am very occasionally getting this error on an _hp Ultrium 3000 LTO-5 8Gb FC,_ it seems to pass the connection tests in L&TT, and hitting "retry" seems to clear the error, but i have to do it manually, so i cant leave it unattended.

Any way to fix it, or increase the number of automatic retries?

**Comment by zhaoyangwx** [comment]
Please make sure no other application or initiator accessing the tape drive being used. Otherwise ioctl will be interrupted due to access conflict. From version 3.5.3 the tape drive is opened exclusively and is supposed to be OK.

**Comment by zhaoyangwx** [comment]
Automatic retry is dangerous and will not be added. Manual inspection is required to prevent hardware damage or data corruption.

**Comment by mlgmaster666** [comment]
Thanks for replying, its giving me the attached error, can you tell if its a software or hardware connection issue?
![Capture1](https://github.com/zhaoyangwx/LTFSCopyGUI/assets/44756386/e0526997-2326-4b2e-b257-ec6845180fe9)

**Comment by zhaoyangwx** [comment]
Not sure. The only thing I can see from the trace log is ioctl failed.

**Comment by mlgmaster666** [comment]
update: it was a pci-e problem, conclusion: L&TT tests are completely fucking useless.

Thanks for taking a look at my problem though.

**Comment by aPuffdog** [comment]
@mlgmaster666 
Hello, I'm facing excactly the same issue, may I ask how you solved the problem, thanks a lot!

**Comment by mlgmaster666** [comment]
> [@mlgmaster666](https://github.com/mlgmaster666) Hello, I'm facing excactly the same issue, may I ask how you solved the problem, thanks a lot!

I replaced my pci-e riser with a better one.

**Comment by aPuffdog** [comment]
> > [@mlgmaster666](https://github.com/mlgmaster666) Hello, I'm facing excactly the same issue, may I ask how you solved the problem, thanks a lot!
> 
> I replaced my pci-e riser with a better one.

got it, thanks a lot
